### ISSUE TITLE
Error when running drush command that outputs a table.

### ISSUE THREAD

**Issue by nlighteneddesign** [consolidation/output-formatters#106]
### Steps to reproduce
What did you do?
Ran drush ms

### Expected behavior
Tell us what should happen
Get a table of current migration statuses

### Actual behavior
Tell us what happens instead
[error]  ValueError: wordwrap(): Argument #4 ($cut_long_words) cannot be true when argument #2 ($width) is 0 in wordwrap() (line 141 of /var/www/html/vendor/consolidation/output-formatters/src/Transformations/WordWrapper.php) #0 /var/www/html/vendor/consolidation/output-formatters/src/Transformations/WordWrapper.php(141): wordwrap('N/A', 0, '\n', true)

### System Configuration
Which O.S. and PHP version are you using?
Linux / DDEV
PHP 8.0

**Comment by nlighteneddesign** [comment]
I opened PR https://github.com/consolidation/output-formatters/pull/107

**Comment by greg-1-anderson** [comment]
Merged, thanks.
