### ISSUE TITLE
Add example of specifying default fields to show in a RowOfFields

### ISSUE THREAD

**Issue by weitzman** [consolidation/output-formatters#35]
Sometimes you wish to show fewer fields by default than are available. What annotation and value  specifies the columns to show show _by default_? Will be used by views-list to hide the Tag column by default.

Also note that views-list is throwing a notice in the adapter that is related.

**Comment by greg-1-anderson** [comment]
`@default-fields`. I'll add documentation.

**Comment by greg-1-anderson** [comment]
This is a test comment.

**Comment by greg-1-anderson** [comment]
Another test comment.

**Comment by greg-1-anderson** [comment]
Identify issue number with argument.

**Comment by greg-1-anderson** [comment]
Fixed as part of #72.
