### ISSUE TITLE
Updating to Drush 8.1.8 is throwing errors

### ISSUE THREAD

**Issue by jrockowitz** [consolidation/output-formatters#48]
### Steps to reproduce

Updated to Drush 8.1.8 on 

> PHP Fatal error:  Cannot use Consolidation\OutputFormatters\FormatterInterface as FormatterInterface because the name is already in use in /home/mskwww/drush/vendor/consolidation/output-formatters/src/Formatters/XmlFormatter.php on line 8

Error was introduced in Drush 8.1.6 when composer version for "consolidation/output-formatters" was changed from "~1" to "^2.0.0-rc1", 

https://github.com/drush-ops/drush/blob/8.1.5/composer.lock
https://github.com/drush-ops/drush/blob/8.1.6/composer.lock

### Expected behavior

Drush should execute without any problems.

### Actual behavior

Drush is failing to execute.

### System Configuration

Red Hat Enterprise Linux Server release 6.8 (Santiago)

PHP 7.0.11 (cli) (built: Sep 14 2016 07:27:30) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
   with Zend OPcache v7.0.11, Copyright (c) 1999-2016, by Zend Technologies

### Additional Notes

Drush is being installed globally using GIT clone with a checkout of the release tag and then running `php ../composer.phar install`

**Comment by greg-1-anderson** [comment]
Cannot reproduce with Drush 8.1.8 or 8.2-dev (HEAD of today's 8.x branch). Please check your install.
