### ISSUE TITLE
Progressive row buidling.

### ISSUE THREAD

**Issue by neclimdul** [consolidation/output-formatters#61]
### Steps to reproduce
It would be really handy to use collection formatters as a data structure directly similar to how Symfony's Table object works.There is no way to progressively build collections in formatters.

### Expected behavior
For example, 
```
<?php
$rows = new RowsOfFields();
foreach ($somedata as $data) {
  $rows->addRow([$data[1], $data[5]);
}
return $rows
?>
```

### Actual behavior
No such functionality exists

### System Configuration
N/A

**Comment by greg-1-anderson** [comment]
Are you looking for incremental output, or merely incremental building, as in your example?

Note that RowsOfFields is an ArrayObject, so you shouldn't have trouble building or manipulating it.  See this [formatter hook example](https://github.com/consolidation/Robo/blob/master/examples/RoboFile.php#L253) in Robo as one illustration of this principal.

It would be easy enough to provide an `addRow()` method. However, note that RowsOfFields expects keys on each row, and keys on each data element within each row. I'm not sure that `addRow()` would add a lot over the already available array syntax.

**Comment by neclimdul** [comment]
ah, the ArrayObject would definitely work. I was thinking down a specific path I guess and the addRow completes in the IDE and was expressive.

> RowsOfFields expects keys on each row, and keys on each data element within each row

The implementations I ran across did something like:

```
<?php
$data = [];

foreach ($somedata as $row) {
  $data[] = [ 
    'foo' => $row[1],
    'bar' => $row[2],
  ];
}
return new RowOfFields($data);
?>
```

Which is why I was thinking it would be better as.
```
<?php
$data = new RowOfFields([]);

foreach ($somedata as $row) {
  $data->addRow([ 
    'foo' => $row[1],
    'bar' => $row[2],
  ]);
}

return $data;
?> 
```

**Comment by greg-1-anderson** [comment]
You should also provide keys for each row:
```
<?php
$data = new RowsOfFields();

foreach ($somedata as $rowkey => $row) {
  $data[$rowkey] = [ 
    'foo' => $row[1],
    'bar' => $row[2],
  ];
}
return $data;
?>
```
Some transformations (e.g. `--format=list`) depend on the row key.  If there is no row key in your source data, but the `foo` column can be considered a key, then you could do something like this:
```
<?php
$data = new RowsOfFields();

foreach ($somedata as $row) {
  $data[$row[1]] = [ 
    'foo' => $row[1],
    'bar' => $row[2],
  ];
}
return $data;
?>
```
So, we could add an `addRow()` method to RowsOfFields & c., but if we did, it should also take a parameter for the row key. I'm not sure if that's much of an improvement over the array-access method shown above.

**Comment by neclimdul** [comment]
Maybe addRow and some additional documentation might be helpful in documenting a concept that isn't clear by "Each row contains an associative array of field:value pairs" because without a purpose " array of field:value pairs" is the only thing that sticks for me. 

I'm still not following how I should key a list because 0,1,2,3,4,5,6 valid key and pretty appropriate for "lists" in a basic sense. Should it be some sort of descriptive value like a title and if so how am I expected to ensure its unique? If its suppose to be an ID and that's generally going to be a number how is a flat array not equally appropriate?

**Comment by greg-1-anderson** [comment]
If you use `0,1,2,3,4,5,6` for your keys, then you will get the following result:
```
$ mytool my:command --format=list
0
1
2
3
4
5
6
```
A PR adding clarifications to the documentation, with or without an addRow method, would be welcome.

**Comment by greg-1-anderson** [comment]
Seems existing functionality / documentation is close enough.
